import type { Domain } from './types.js';

/**
 * The locked IT-domain taxonomy: 20 domains, each expanding into hundreds of
 * role aliases at enrichment time. This is the authored source of truth —
 * edit here to add or tune a domain. Ported verbatim from the legacy engine.
 */
export const DOMAIN_TAXONOMY: readonly Domain[] = [
  {
    slug: 'ai_ml_genai',
    label: 'AI, Machine Learning and GenAI',
    inputAliases: ['ai', 'ml', 'genai', 'ai ml', 'ai engineer', 'machine learning', 'llm'],
    searchQueries: [
      'AI Engineer',
      'Machine Learning Engineer',
      'LLM Engineer',
      'MLOps Engineer',
      'Data Scientist',
    ],
    coreRoles: [
      'AI Engineer',
      'Machine Learning Engineer',
      'ML Engineer',
      'Applied AI Engineer',
      'Generative AI Engineer',
      'GenAI Engineer',
      'LLM Engineer',
      'MLOps Engineer',
      'NLP Engineer',
      'Computer Vision Engineer',
      'Deep Learning Engineer',
      'AI Research Engineer',
      'Applied Scientist',
      'Data Scientist',
      'AI Automation Engineer',
      'Prompt Engineer',
      'AI Product Engineer',
      'AI Solutions Engineer',
    ],
    terms: [
      'artificial intelligence',
      'machine learning',
      'generative ai',
      'genai',
      'llm',
      'rag',
      'nlp',
      'computer vision',
      'deep learning',
      'pytorch',
      'tensorflow',
      'mlops',
      'model deployment',
      'langchain',
      'vector database',
      'embeddings',
    ],
  },
  {
    slug: 'software_engineering',
    label: 'Software Engineering',
    inputAliases: ['software', 'software engineer', 'application developer', 'developer'],
    searchQueries: [
      'Software Engineer',
      'Software Developer',
      'Application Developer',
      'Python Developer',
      'Java Developer',
    ],
    coreRoles: [
      'Software Engineer',
      'Software Developer',
      'Application Developer',
      'Systems Software Engineer',
      'Platform Software Engineer',
      'API Engineer',
      'Integration Engineer',
      'Tools Engineer',
      'Runtime Engineer',
      'Embedded Software Engineer',
      'Enterprise Application Developer',
      'Java Developer',
      'Python Developer',
      '.NET Developer',
      'C++ Developer',
      'Go Developer',
      'Rust Developer',
    ],
    terms: [
      'software development',
      'application development',
      'api',
      'system design',
      'python',
      'java',
      'javascript',
      'typescript',
      'c#',
      '.net',
      'go',
      'rust',
      'testing',
      'debugging',
    ],
  },
  {
    slug: 'backend_engineering',
    label: 'Backend Engineering',
    inputAliases: ['backend', 'back end', 'server side', 'api backend'],
    searchQueries: [
      'Backend Engineer',
      'Back End Engineer',
      'API Engineer',
      'Microservices Engineer',
      'Java Backend Developer',
    ],
    coreRoles: [
      'Backend Engineer',
      'Back End Engineer',
      'Server Side Engineer',
      'API Engineer',
      'Microservices Engineer',
      'Distributed Systems Engineer',
      'Cloud Backend Engineer',
      'Java Backend Developer',
      'Python Backend Developer',
      'Go Backend Developer',
      'Node.js Backend Developer',
      'Ruby Backend Developer',
      'Platform API Engineer',
      'Payments Backend Engineer',
      'Backend Software Developer',
    ],
    terms: [
      'backend',
      'api',
      'microservices',
      'distributed systems',
      'rest',
      'graphql',
      'postgresql',
      'mysql',
      'redis',
      'kafka',
      'queues',
      'node.js',
      'java',
      'go',
      'python',
    ],
  },
  {
    slug: 'frontend_web',
    label: 'Frontend and Web Engineering',
    inputAliases: ['frontend', 'front end', 'web', 'ui engineer', 'react'],
    searchQueries: [
      'Frontend Engineer',
      'Front End Engineer',
      'React Developer',
      'Web Developer',
      'UI Engineer',
    ],
    coreRoles: [
      'Frontend Engineer',
      'Front End Engineer',
      'Web Developer',
      'UI Engineer',
      'React Developer',
      'Vue Developer',
      'Angular Developer',
      'JavaScript Developer',
      'TypeScript Developer',
      'Web Application Engineer',
      'Design Systems Engineer',
      'Frontend Platform Engineer',
      'UX Engineer',
      'Accessibility Engineer',
      'Shopify Developer',
      'WordPress Developer',
    ],
    terms: [
      'frontend',
      'front end',
      'web application',
      'react',
      'vue',
      'angular',
      'javascript',
      'typescript',
      'html',
      'css',
      'accessibility',
      'design systems',
      'next.js',
      'ui',
    ],
  },
  {
    slug: 'full_stack',
    label: 'Full Stack Engineering',
    inputAliases: ['full stack', 'fullstack', 'mern', 'mean', 'product engineer'],
    searchQueries: [
      'Full Stack Engineer',
      'Full Stack Developer',
      'Product Engineer',
      'React Node Developer',
      'Next.js Developer',
    ],
    coreRoles: [
      'Full Stack Engineer',
      'Fullstack Engineer',
      'Full Stack Developer',
      'Web Engineer',
      'Product Engineer',
      'Software Engineer Full Stack',
      'MERN Stack Developer',
      'MEAN Stack Developer',
      'React Node Developer',
      'Next.js Developer',
      'Django React Developer',
      'Rails Full Stack Developer',
      'Java Full Stack Developer',
      '.NET Full Stack Developer',
    ],
    terms: [
      'full stack',
      'frontend',
      'backend',
      'react',
      'node.js',
      'next.js',
      'django',
      'rails',
      'api',
      'postgresql',
      'typescript',
      'javascript',
    ],
  },
  {
    slug: 'data_engineering',
    label: 'Data Engineering',
    inputAliases: ['data engineering', 'data engineer', 'etl', 'elt', 'data platform'],
    searchQueries: [
      'Data Engineer',
      'Analytics Engineer',
      'Data Platform Engineer',
      'ETL Developer',
      'Spark Engineer',
    ],
    coreRoles: [
      'Data Engineer',
      'Analytics Engineer',
      'Big Data Engineer',
      'ETL Developer',
      'ELT Developer',
      'Data Pipeline Engineer',
      'Spark Engineer',
      'Airflow Engineer',
      'Data Platform Engineer',
      'Warehouse Engineer',
      'Lakehouse Engineer',
      'Streaming Data Engineer',
      'Kafka Data Engineer',
      'Cloud Data Engineer',
      'DBT Engineer',
      'DataOps Engineer',
    ],
    terms: [
      'data engineering',
      'etl',
      'elt',
      'pipeline',
      'spark',
      'airflow',
      'dbt',
      'warehouse',
      'lakehouse',
      'snowflake',
      'bigquery',
      'databricks',
      'kafka',
      'sql',
    ],
  },
  {
    slug: 'data_analytics_bi',
    label: 'Data Analytics and Business Intelligence',
    inputAliases: ['analytics', 'data analyst', 'bi', 'business intelligence', 'reporting'],
    searchQueries: [
      'Data Analyst',
      'Business Intelligence Analyst',
      'BI Developer',
      'Product Analyst',
      'Power BI Developer',
    ],
    coreRoles: [
      'Data Analyst',
      'Business Intelligence Analyst',
      'BI Developer',
      'Reporting Analyst',
      'Analytics Consultant',
      'Product Analyst',
      'Marketing Data Analyst',
      'Operations Analyst',
      'Tableau Developer',
      'Power BI Developer',
      'Looker Developer',
      'SQL Analyst',
      'Insights Analyst',
      'Growth Analyst',
      'Revenue Analyst',
    ],
    terms: [
      'analytics',
      'business intelligence',
      'dashboard',
      'reporting',
      'sql',
      'tableau',
      'power bi',
      'looker',
      'excel',
      'insights',
      'metrics',
      'kpi',
    ],
  },
  {
    slug: 'cloud_engineering',
    label: 'Cloud Engineering',
    inputAliases: ['cloud', 'aws', 'azure', 'gcp', 'cloud infrastructure'],
    searchQueries: [
      'Cloud Engineer',
      'AWS Engineer',
      'Azure Engineer',
      'GCP Engineer',
      'Cloud Infrastructure Engineer',
    ],
    coreRoles: [
      'Cloud Engineer',
      'AWS Engineer',
      'Azure Engineer',
      'GCP Engineer',
      'Cloud Infrastructure Engineer',
      'Cloud Operations Engineer',
      'Cloud Platform Engineer',
      'Cloud Automation Engineer',
      'Cloud Migration Engineer',
      'Cloud Support Engineer',
      'Cloud Solutions Engineer',
      'Cloud Systems Engineer',
      'Terraform Engineer',
      'Kubernetes Cloud Engineer',
    ],
    terms: [
      'cloud',
      'aws',
      'azure',
      'gcp',
      'terraform',
      'kubernetes',
      'docker',
      'iam',
      'ec2',
      'lambda',
      'eks',
      'aks',
      'gke',
      'cloud migration',
      'infrastructure',
    ],
  },
  {
    slug: 'devops_platform_sre',
    label: 'DevOps, Platform and Site Reliability',
    inputAliases: ['devops', 'platform', 'sre', 'site reliability', 'infrastructure engineer'],
    searchQueries: [
      'DevOps Engineer',
      'Platform Engineer',
      'Site Reliability Engineer',
      'SRE',
      'Infrastructure Engineer',
    ],
    coreRoles: [
      'DevOps Engineer',
      'Platform Engineer',
      'Site Reliability Engineer',
      'SRE',
      'Infrastructure Engineer',
      'CI/CD Engineer',
      'Release Engineer',
      'Build Engineer',
      'Kubernetes Engineer',
      'Observability Engineer',
      'Production Engineer',
      'Linux Platform Engineer',
      'Systems Reliability Engineer',
      'Cloud DevOps Engineer',
      'IaC Engineer',
    ],
    terms: [
      'devops',
      'platform engineering',
      'site reliability',
      'sre',
      'ci/cd',
      'kubernetes',
      'terraform',
      'linux',
      'observability',
      'prometheus',
      'grafana',
      'incident response',
      'automation',
    ],
  },
  {
    slug: 'cybersecurity',
    label: 'Cybersecurity',
    inputAliases: ['cybersecurity', 'cyber security', 'security', 'soc', 'appsec'],
    searchQueries: [
      'Cyber Security Engineer',
      'Security Engineer',
      'SOC Analyst',
      'Application Security Engineer',
      'Cloud Security Engineer',
    ],
    coreRoles: [
      'Security Engineer',
      'Cyber Security Engineer',
      'SOC Analyst',
      'Information Security Analyst',
      'Application Security Engineer',
      'AppSec Engineer',
      'Cloud Security Engineer',
      'Security Operations Engineer',
      'Detection Engineer',
      'Incident Response Analyst',
      'Vulnerability Analyst',
      'Penetration Tester',
      'IAM Engineer',
      'GRC Analyst',
      'Security Automation Engineer',
      'Product Security Engineer',
    ],
    terms: [
      'security',
      'cybersecurity',
      'soc',
      'siem',
      'vulnerability',
      'incident response',
      'appsec',
      'cloud security',
      'iam',
      'penetration testing',
      'threat detection',
      'grc',
      'compliance',
    ],
  },
  {
    slug: 'qa_test_automation',
    label: 'QA and Test Automation',
    inputAliases: ['qa', 'quality assurance', 'test automation', 'sdet', 'tester'],
    searchQueries: [
      'QA Engineer',
      'Test Automation Engineer',
      'SDET',
      'Software Test Engineer',
      'QA Automation Engineer',
    ],
    coreRoles: [
      'QA Engineer',
      'Test Engineer',
      'Automation Test Engineer',
      'SDET',
      'Software Development Engineer in Test',
      'Manual QA Tester',
      'QA Analyst',
      'Quality Engineer',
      'Test Automation Developer',
      'Performance Test Engineer',
      'API Test Engineer',
      'Mobile QA Engineer',
      'Web QA Engineer',
      'Regression Test Engineer',
      'QA Automation Engineer',
    ],
    terms: [
      'qa',
      'quality assurance',
      'test automation',
      'sdet',
      'selenium',
      'cypress',
      'playwright',
      'api testing',
      'manual testing',
      'regression',
      'performance testing',
      'test cases',
    ],
  },
  {
    slug: 'mobile_development',
    label: 'Mobile Development',
    inputAliases: ['mobile', 'ios', 'android', 'react native', 'flutter'],
    searchQueries: [
      'Mobile Developer',
      'iOS Developer',
      'Android Developer',
      'React Native Developer',
      'Flutter Developer',
    ],
    coreRoles: [
      'Mobile Developer',
      'Mobile Engineer',
      'iOS Developer',
      'Android Developer',
      'React Native Developer',
      'Flutter Developer',
      'Kotlin Developer',
      'Swift Developer',
      'Mobile App Developer',
      'iOS Engineer',
      'Android Engineer',
      'Cross Platform Mobile Engineer',
      'Mobile Platform Engineer',
      'Wearables Developer',
    ],
    terms: [
      'mobile',
      'ios',
      'android',
      'swift',
      'kotlin',
      'react native',
      'flutter',
      'xcode',
      'android studio',
      'app store',
      'play store',
    ],
  },
  {
    slug: 'database_dba',
    label: 'Database Engineering and DBA',
    inputAliases: ['database', 'dba', 'sql developer', 'database engineer'],
    searchQueries: [
      'Database Engineer',
      'Database Administrator',
      'SQL Developer',
      'PostgreSQL Developer',
      'Database Reliability Engineer',
    ],
    coreRoles: [
      'Database Administrator',
      'DBA',
      'Database Engineer',
      'SQL Developer',
      'PostgreSQL Developer',
      'MySQL DBA',
      'Oracle DBA',
      'SQL Server DBA',
      'Database Reliability Engineer',
      'Data Platform DBA',
      'Database Performance Engineer',
      'ETL Database Developer',
      'MongoDB Database Engineer',
      'NoSQL Database Engineer',
    ],
    terms: [
      'database',
      'dba',
      'sql',
      'postgresql',
      'mysql',
      'oracle',
      'sql server',
      'mongodb',
      'nosql',
      'replication',
      'query tuning',
      'backup',
      'performance',
    ],
  },
  {
    slug: 'it_support_sysadmin',
    label: 'IT Support and Systems Administration',
    inputAliases: ['it support', 'sysadmin', 'system administrator', 'help desk', 'service desk'],
    searchQueries: [
      'IT Support Engineer',
      'Systems Administrator',
      'Desktop Support Engineer',
      'Service Desk Analyst',
      'Technical Support Engineer',
    ],
    coreRoles: [
      'IT Support Engineer',
      'Technical Support Engineer',
      'Desktop Support Engineer',
      'Help Desk Analyst',
      'Service Desk Analyst',
      'Systems Administrator',
      'Linux Administrator',
      'Windows Administrator',
      'IT Operations Engineer',
      'End User Computing Engineer',
      'Field Support Engineer',
      'Application Support Analyst',
      'IT Technician',
      'Support Specialist',
    ],
    terms: [
      'it support',
      'help desk',
      'service desk',
      'systems administrator',
      'linux',
      'windows',
      'active directory',
      'office 365',
      'endpoint',
      'ticketing',
      'hardware',
      'desktop support',
    ],
  },
  {
    slug: 'network_engineering',
    label: 'Network Engineering',
    inputAliases: ['network', 'networking', 'noc', 'network engineer'],
    searchQueries: [
      'Network Engineer',
      'NOC Engineer',
      'Network Administrator',
      'Network Security Engineer',
      'Cloud Network Engineer',
    ],
    coreRoles: [
      'Network Engineer',
      'Network Administrator',
      'NOC Engineer',
      'Network Operations Engineer',
      'Infrastructure Network Engineer',
      'Cisco Network Engineer',
      'Firewall Engineer',
      'Wireless Network Engineer',
      'Network Security Engineer',
      'Telecoms Engineer',
      'Network Support Engineer',
      'SD-WAN Engineer',
      'Cloud Network Engineer',
      'Network Automation Engineer',
    ],
    terms: [
      'network',
      'networking',
      'noc',
      'cisco',
      'routing',
      'switching',
      'firewall',
      'vpn',
      'sd-wan',
      'wireless',
      'tcp/ip',
      'dns',
      'dhcp',
      'bgp',
    ],
  },
  {
    slug: 'product_technical_product',
    label: 'Product and Technical Product',
    inputAliases: [
      'product',
      'technical product',
      'product owner',
      'product analyst',
      'business analyst',
    ],
    searchQueries: [
      'Technical Product Manager',
      'Product Owner',
      'Product Analyst',
      'Business Analyst',
      'Associate Product Manager',
    ],
    coreRoles: [
      'Product Manager',
      'Technical Product Manager',
      'Product Owner',
      'Associate Product Manager',
      'Product Analyst',
      'Business Analyst',
      'Technical Business Analyst',
      'Product Operations Analyst',
      'Technical Project Manager',
      'Technical Program Manager',
      'Scrum Master',
      'Agile Business Analyst',
      'Platform Product Manager',
      'Data Product Manager',
    ],
    terms: [
      'product',
      'roadmap',
      'requirements',
      'user stories',
      'backlog',
      'stakeholder',
      'analytics',
      'go-to-market',
      'scrum',
      'agile',
      'product operations',
    ],
  },
  {
    slug: 'solutions_presales_customer',
    label: 'Solutions, Presales and Customer Engineering',
    inputAliases: [
      'solutions',
      'presales',
      'pre sales',
      'customer engineer',
      'sales engineer',
      'solution architect',
    ],
    searchQueries: [
      'Solutions Engineer',
      'Sales Engineer',
      'Customer Engineer',
      'Implementation Engineer',
      'Technical Consultant',
    ],
    coreRoles: [
      'Solutions Engineer',
      'Sales Engineer',
      'Pre-Sales Engineer',
      'Customer Engineer',
      'Solutions Architect',
      'Technical Account Manager',
      'Customer Success Engineer',
      'Implementation Engineer',
      'Integration Consultant',
      'Partner Engineer',
      'Developer Advocate',
      'Field Engineer',
      'Professional Services Engineer',
      'Technical Consultant',
    ],
    terms: [
      'solutions engineering',
      'presales',
      'pre-sales',
      'customer engineering',
      'implementation',
      'integration',
      'solution architecture',
      'technical consulting',
      'proof of concept',
      'demo',
    ],
  },
  {
    slug: 'automation_rpa_low_code',
    label: 'Automation, RPA and Low Code',
    inputAliases: ['automation', 'rpa', 'low code', 'no code', 'workflow automation', 'n8n'],
    searchQueries: [
      'Automation Engineer',
      'RPA Developer',
      'Power Automate Developer',
      'Workflow Automation Engineer',
      'Low Code Developer',
    ],
    coreRoles: [
      'Automation Engineer',
      'RPA Developer',
      'RPA Engineer',
      'UiPath Developer',
      'Power Automate Developer',
      'n8n Automation Developer',
      'Zapier Automation Specialist',
      'Workflow Automation Engineer',
      'Business Process Automation Engineer',
      'Low Code Developer',
      'No Code Developer',
      'Process Automation Analyst',
      'Automation Consultant',
      'AI Automation Developer',
    ],
    terms: [
      'automation',
      'rpa',
      'uipath',
      'power automate',
      'n8n',
      'zapier',
      'make.com',
      'workflow',
      'low code',
      'no code',
      'process automation',
      'business process',
    ],
  },
  {
    slug: 'blockchain_web3',
    label: 'Blockchain and Web3',
    inputAliases: ['blockchain', 'web3', 'crypto', 'solidity', 'smart contract'],
    searchQueries: [
      'Blockchain Developer',
      'Web3 Developer',
      'Solidity Developer',
      'Smart Contract Engineer',
      'Protocol Engineer',
    ],
    coreRoles: [
      'Blockchain Developer',
      'Blockchain Engineer',
      'Web3 Developer',
      'Solidity Developer',
      'Smart Contract Engineer',
      'Protocol Engineer',
      'DeFi Engineer',
      'Crypto Backend Engineer',
      'Ethereum Developer',
      'Rust Blockchain Developer',
      'Substrate Developer',
      'dApp Developer',
      'Web3 Frontend Developer',
      'Wallet Engineer',
    ],
    terms: [
      'blockchain',
      'web3',
      'solidity',
      'smart contract',
      'ethereum',
      'defi',
      'wallet',
      'protocol',
      'rust',
      'substrate',
      'dapp',
      'crypto',
    ],
  },
  {
    slug: 'game_ar_vr',
    label: 'Game, AR, VR and Simulation',
    inputAliases: ['game', 'gaming', 'ar', 'vr', 'xr', 'unity', 'unreal'],
    searchQueries: [
      'Game Developer',
      'Unity Developer',
      'Unreal Developer',
      'Gameplay Programmer',
      'XR Developer',
    ],
    coreRoles: [
      'Game Developer',
      'Gameplay Programmer',
      'Unity Developer',
      'Unreal Developer',
      'Game Engineer',
      'AR Developer',
      'VR Developer',
      'XR Developer',
      'Simulation Engineer',
      'Technical Artist',
      'Tools Programmer',
      'Engine Programmer',
      'Graphics Programmer',
      'C# Game Developer',
      'C++ Game Developer',
    ],
    terms: [
      'game development',
      'unity',
      'unreal',
      'gameplay',
      'ar',
      'vr',
      'xr',
      'simulation',
      'c#',
      'c++',
      'graphics',
      'engine',
    ],
  },
];
